<?php

return [
    'Arusha'           => 'Arusha',
    'Dar es Salaam'    => 'Dar es Salaam',
    'Dodoma'           => 'Dodoma',
    'Geita'            => 'Geita',
    'Iringa'           => 'Iringa',
    'Kagera'           => 'Kagera',
    'Kaskazini Pemba'  => 'Kaskazini Pemba',
    'kaskazini Unguja' => 'Kaskazini Unguja',
    'Katavi'           => 'Katavi',
    'Kigoma'           => 'Kigoma',
    'Kilimanjaro'      => 'Kilimanjaro',
    'Kusini Pemba'     => 'Kusini Pemba',
    'Kusini Unguja'    => 'Kusini Unguja',
    'Lindi'            => 'Lindi',
    'Manyara'          => 'Manyara',
    'Mara'             => 'Mara',
    'Mbeya'            => 'Mbeya',
    'Mjini Magharibi'  => 'Mjini Magharibi',
    'Morogoro'         => 'Morogoro',
    'Mtwara'           => 'Mtwara',
    'Mwanza'           => 'Mwanza',
    'Njombe'           => 'Njombe',
    'Pwani'            => 'Pwani',
    'Rukwa'            => 'Rukwa',
    'Ruvuma'           => 'Ruvuma',
    'Shinyanga'        => 'Shinyanga',
    'Simiyu'           => 'Simiyu',
    'Singida'          => 'Singida',
    'Tabora'           => 'Tabora',
    'Tanga'            => 'Tanga'
];
